#############################################################################
# Makefile for building: tetrix
# Generated by qmake (2.01a) (Qt 4.8.6) on: Sat Oct 8 19:05:51 2016
# Project:  tetrix.pro
# Template: app
# Command: /usr/local/software/qt4/bin/qmake -o Makefile tetrix.pro
#############################################################################

####### Compiler, tools and options

CC            = gcc
CXX           = g++
DEFINES       = -DQT_NO_DEBUG -DQT_QT3SUPPORT_LIB -DQT3_SUPPORT -DQT_GUI_LIB -DQT_CORE_LIB -DQT_SHARED
CFLAGS        = -m64 -pipe -O2 -Wall -W -D_REENTRANT $(DEFINES)
CXXFLAGS      = -m64 -pipe -O2 -Wall -W -D_REENTRANT $(DEFINES)
INCPATH       = -I/usr/local/software/qt-4.8.6/mkspecs/linux-g++-64 -I. -I/usr/local/software/qt-4.8.6/include/QtCore -I/usr/local/software/qt-4.8.6/include/QtGui -I/usr/local/software/qt-4.8.6/include/Qt3Support -I/usr/local/software/qt-4.8.6/include -I.
LINK          = g++
LFLAGS        = -m64 -Wl,-O1 -Wl,-rpath,/usr/local/software/qt-4.8.6/lib
LIBS          = $(SUBLIBS)  -L/usr/local/software/qt-4.8.6/lib -lQt3Support -Wl,-rpath,/usr/local/software/qt4/lib -L/usr/local/software/qt4/lib -lQtSql -Wl,-rpath,/usr/local/software/qt4/lib -Wl,-rpath,/usr/local/software/qt4/lib -Wl,-rpath,/usr/local/software/qt4/lib -Wl,-rpath,/usr/local/software/qt4/lib -lQtXml -Wl,-rpath,/usr/local/software/qt4/lib -Wl,-rpath,/usr/local/software/qt4/lib -Wl,-rpath,/usr/local/software/qt4/lib -Wl,-rpath,/usr/local/software/qt4/lib -L/usr/X11R6/lib64 -Wl,-rpath,/usr/local/software/qt4/lib -Wl,-rpath,/usr/local/software/qt4/lib -lQtNetwork -Wl,-rpath,/usr/local/software/qt4/lib -Wl,-rpath,/usr/local/software/qt4/lib -Wl,-rpath,/usr/local/software/qt4/lib -Wl,-rpath,/usr/local/software/qt4/lib -lQtGui -Wl,-rpath,/usr/local/software/qt4/lib -Wl,-rpath,/usr/local/software/qt4/lib -Wl,-rpath,/usr/local/software/qt4/lib -lQtCore -Wl,-rpath,/usr/local/software/qt4/lib -lpthread 
AR            = ar cqs
RANLIB        = 
QMAKE         = /usr/local/software/qt4/bin/qmake
TAR           = tar -cf
COMPRESS      = gzip -9f
COPY          = cp -f
SED           = sed
COPY_FILE     = $(COPY)
COPY_DIR      = $(COPY) -r
STRIP         = strip
INSTALL_FILE  = install -m 644 -p
INSTALL_DIR   = $(COPY_DIR)
INSTALL_PROGRAM = install -m 755 -p
DEL_FILE      = rm -f
SYMLINK       = ln -f -s
DEL_DIR       = rmdir
MOVE          = mv -f
CHK_DIR_EXISTS= test -d
MKDIR         = mkdir -p

####### Output directory

OBJECTS_DIR   = ./

####### Files

SOURCES       = main.cpp \
		window.cpp \
		board.cpp \
		preview.cpp \
		item.cpp \
		state.cpp moc_window.cpp \
		moc_board.cpp \
		moc_preview.cpp \
		moc_state.cpp
OBJECTS       = main.o \
		window.o \
		board.o \
		preview.o \
		item.o \
		state.o \
		moc_window.o \
		moc_board.o \
		moc_preview.o \
		moc_state.o
DIST          = /usr/local/software/qt-4.8.6/mkspecs/common/unix.conf \
		/usr/local/software/qt-4.8.6/mkspecs/common/linux.conf \
		/usr/local/software/qt-4.8.6/mkspecs/common/gcc-base.conf \
		/usr/local/software/qt-4.8.6/mkspecs/common/gcc-base-unix.conf \
		/usr/local/software/qt-4.8.6/mkspecs/common/g++-base.conf \
		/usr/local/software/qt-4.8.6/mkspecs/common/g++-unix.conf \
		/usr/local/software/qt-4.8.6/mkspecs/qconfig.pri \
		/usr/local/software/qt-4.8.6/mkspecs/modules/qt_webkit_version.pri \
		/usr/local/software/qt-4.8.6/mkspecs/features/qt_functions.prf \
		/usr/local/software/qt-4.8.6/mkspecs/features/qt_config.prf \
		/usr/local/software/qt-4.8.6/mkspecs/features/exclusive_builds.prf \
		/usr/local/software/qt-4.8.6/mkspecs/features/default_pre.prf \
		/usr/local/software/qt-4.8.6/mkspecs/features/release.prf \
		/usr/local/software/qt-4.8.6/mkspecs/features/default_post.prf \
		/usr/local/software/qt-4.8.6/mkspecs/features/shared.prf \
		/usr/local/software/qt-4.8.6/mkspecs/features/unix/gdb_dwarf_index.prf \
		/usr/local/software/qt-4.8.6/mkspecs/features/warn_on.prf \
		/usr/local/software/qt-4.8.6/mkspecs/features/qt.prf \
		/usr/local/software/qt-4.8.6/mkspecs/features/unix/thread.prf \
		/usr/local/software/qt-4.8.6/mkspecs/features/moc.prf \
		/usr/local/software/qt-4.8.6/mkspecs/features/resources.prf \
		/usr/local/software/qt-4.8.6/mkspecs/features/uic.prf \
		/usr/local/software/qt-4.8.6/mkspecs/features/yacc.prf \
		/usr/local/software/qt-4.8.6/mkspecs/features/lex.prf \
		/usr/local/software/qt-4.8.6/mkspecs/features/include_source_dir.prf \
		tetrix.pro
QMAKE_TARGET  = tetrix
DESTDIR       = 
TARGET        = tetrix

first: all
####### Implicit rules

.SUFFIXES: .o .c .cpp .cc .cxx .C

.cpp.o:
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o "$@" "$<"

.cc.o:
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o "$@" "$<"

.cxx.o:
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o "$@" "$<"

.C.o:
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o "$@" "$<"

.c.o:
	$(CC) -c $(CFLAGS) $(INCPATH) -o "$@" "$<"

####### Build rules

all: Makefile $(TARGET)

$(TARGET):  $(OBJECTS)  
	$(LINK) $(LFLAGS) -o $(TARGET) $(OBJECTS) $(OBJCOMP) $(LIBS)

Makefile: tetrix.pro  /usr/local/software/qt-4.8.6/mkspecs/linux-g++-64/qmake.conf /usr/local/software/qt-4.8.6/mkspecs/common/unix.conf \
		/usr/local/software/qt-4.8.6/mkspecs/common/linux.conf \
		/usr/local/software/qt-4.8.6/mkspecs/common/gcc-base.conf \
		/usr/local/software/qt-4.8.6/mkspecs/common/gcc-base-unix.conf \
		/usr/local/software/qt-4.8.6/mkspecs/common/g++-base.conf \
		/usr/local/software/qt-4.8.6/mkspecs/common/g++-unix.conf \
		/usr/local/software/qt-4.8.6/mkspecs/qconfig.pri \
		/usr/local/software/qt-4.8.6/mkspecs/modules/qt_webkit_version.pri \
		/usr/local/software/qt-4.8.6/mkspecs/features/qt_functions.prf \
		/usr/local/software/qt-4.8.6/mkspecs/features/qt_config.prf \
		/usr/local/software/qt-4.8.6/mkspecs/features/exclusive_builds.prf \
		/usr/local/software/qt-4.8.6/mkspecs/features/default_pre.prf \
		/usr/local/software/qt-4.8.6/mkspecs/features/release.prf \
		/usr/local/software/qt-4.8.6/mkspecs/features/default_post.prf \
		/usr/local/software/qt-4.8.6/mkspecs/features/shared.prf \
		/usr/local/software/qt-4.8.6/mkspecs/features/unix/gdb_dwarf_index.prf \
		/usr/local/software/qt-4.8.6/mkspecs/features/warn_on.prf \
		/usr/local/software/qt-4.8.6/mkspecs/features/qt.prf \
		/usr/local/software/qt-4.8.6/mkspecs/features/unix/thread.prf \
		/usr/local/software/qt-4.8.6/mkspecs/features/moc.prf \
		/usr/local/software/qt-4.8.6/mkspecs/features/resources.prf \
		/usr/local/software/qt-4.8.6/mkspecs/features/uic.prf \
		/usr/local/software/qt-4.8.6/mkspecs/features/yacc.prf \
		/usr/local/software/qt-4.8.6/mkspecs/features/lex.prf \
		/usr/local/software/qt-4.8.6/mkspecs/features/include_source_dir.prf \
		/usr/local/software/qt-4.8.6/lib/libQt3Support.prl \
		/usr/local/software/qt-4.8.6/lib/libQtSql.prl \
		/usr/local/software/qt-4.8.6/lib/libQtCore.prl \
		/usr/local/software/qt-4.8.6/lib/libQtXml.prl \
		/usr/local/software/qt-4.8.6/lib/libQtGui.prl \
		/usr/local/software/qt-4.8.6/lib/libQtNetwork.prl
	$(QMAKE) -o Makefile tetrix.pro
/usr/local/software/qt-4.8.6/mkspecs/common/unix.conf:
/usr/local/software/qt-4.8.6/mkspecs/common/linux.conf:
/usr/local/software/qt-4.8.6/mkspecs/common/gcc-base.conf:
/usr/local/software/qt-4.8.6/mkspecs/common/gcc-base-unix.conf:
/usr/local/software/qt-4.8.6/mkspecs/common/g++-base.conf:
/usr/local/software/qt-4.8.6/mkspecs/common/g++-unix.conf:
/usr/local/software/qt-4.8.6/mkspecs/qconfig.pri:
/usr/local/software/qt-4.8.6/mkspecs/modules/qt_webkit_version.pri:
/usr/local/software/qt-4.8.6/mkspecs/features/qt_functions.prf:
/usr/local/software/qt-4.8.6/mkspecs/features/qt_config.prf:
/usr/local/software/qt-4.8.6/mkspecs/features/exclusive_builds.prf:
/usr/local/software/qt-4.8.6/mkspecs/features/default_pre.prf:
/usr/local/software/qt-4.8.6/mkspecs/features/release.prf:
/usr/local/software/qt-4.8.6/mkspecs/features/default_post.prf:
/usr/local/software/qt-4.8.6/mkspecs/features/shared.prf:
/usr/local/software/qt-4.8.6/mkspecs/features/unix/gdb_dwarf_index.prf:
/usr/local/software/qt-4.8.6/mkspecs/features/warn_on.prf:
/usr/local/software/qt-4.8.6/mkspecs/features/qt.prf:
/usr/local/software/qt-4.8.6/mkspecs/features/unix/thread.prf:
/usr/local/software/qt-4.8.6/mkspecs/features/moc.prf:
/usr/local/software/qt-4.8.6/mkspecs/features/resources.prf:
/usr/local/software/qt-4.8.6/mkspecs/features/uic.prf:
/usr/local/software/qt-4.8.6/mkspecs/features/yacc.prf:
/usr/local/software/qt-4.8.6/mkspecs/features/lex.prf:
/usr/local/software/qt-4.8.6/mkspecs/features/include_source_dir.prf:
/usr/local/software/qt-4.8.6/lib/libQt3Support.prl:
/usr/local/software/qt-4.8.6/lib/libQtSql.prl:
/usr/local/software/qt-4.8.6/lib/libQtCore.prl:
/usr/local/software/qt-4.8.6/lib/libQtXml.prl:
/usr/local/software/qt-4.8.6/lib/libQtGui.prl:
/usr/local/software/qt-4.8.6/lib/libQtNetwork.prl:
qmake:  FORCE
	@$(QMAKE) -o Makefile tetrix.pro

dist: 
	@$(CHK_DIR_EXISTS) .tmp/tetrix1.0.0 || $(MKDIR) .tmp/tetrix1.0.0 
	$(COPY_FILE) --parents $(SOURCES) $(DIST) .tmp/tetrix1.0.0/ && $(COPY_FILE) --parents window.h board.h preview.h item.h state.h .tmp/tetrix1.0.0/ && $(COPY_FILE) --parents main.cpp window.cpp board.cpp preview.cpp item.cpp state.cpp .tmp/tetrix1.0.0/ && (cd `dirname .tmp/tetrix1.0.0` && $(TAR) tetrix1.0.0.tar tetrix1.0.0 && $(COMPRESS) tetrix1.0.0.tar) && $(MOVE) `dirname .tmp/tetrix1.0.0`/tetrix1.0.0.tar.gz . && $(DEL_FILE) -r .tmp/tetrix1.0.0


clean:compiler_clean 
	-$(DEL_FILE) $(OBJECTS)
	-$(DEL_FILE) *~ core *.core


####### Sub-libraries

distclean: clean
	-$(DEL_FILE) $(TARGET) 
	-$(DEL_FILE) Makefile


check: first

mocclean: compiler_moc_header_clean compiler_moc_source_clean

mocables: compiler_moc_header_make_all compiler_moc_source_make_all

compiler_moc_header_make_all: moc_window.cpp moc_board.cpp moc_preview.cpp moc_state.cpp
compiler_moc_header_clean:
	-$(DEL_FILE) moc_window.cpp moc_board.cpp moc_preview.cpp moc_state.cpp
moc_window.cpp: board.h \
		preview.h \
		state.h \
		item.h \
		window.h
	/usr/local/software/qt-4.8.6/bin/moc $(DEFINES) $(INCPATH) window.h -o moc_window.cpp

moc_board.cpp: board.h
	/usr/local/software/qt-4.8.6/bin/moc $(DEFINES) $(INCPATH) board.h -o moc_board.cpp

moc_preview.cpp: preview.h
	/usr/local/software/qt-4.8.6/bin/moc $(DEFINES) $(INCPATH) preview.h -o moc_preview.cpp

moc_state.cpp: item.h \
		state.h
	/usr/local/software/qt-4.8.6/bin/moc $(DEFINES) $(INCPATH) state.h -o moc_state.cpp

compiler_rcc_make_all:
compiler_rcc_clean:
compiler_image_collection_make_all: qmake_image_collection.cpp
compiler_image_collection_clean:
	-$(DEL_FILE) qmake_image_collection.cpp
compiler_moc_source_make_all:
compiler_moc_source_clean:
compiler_uic_make_all:
compiler_uic_clean:
compiler_yacc_decl_make_all:
compiler_yacc_decl_clean:
compiler_yacc_impl_make_all:
compiler_yacc_impl_clean:
compiler_lex_make_all:
compiler_lex_clean:
compiler_clean: compiler_moc_header_clean 

####### Compile

main.o: main.cpp window.h \
		board.h \
		preview.h \
		state.h \
		item.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o main.o main.cpp

window.o: window.cpp window.h \
		board.h \
		preview.h \
		state.h \
		item.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o window.o window.cpp

board.o: board.cpp window.h \
		board.h \
		preview.h \
		state.h \
		item.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o board.o board.cpp

preview.o: preview.cpp window.h \
		board.h \
		preview.h \
		state.h \
		item.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o preview.o preview.cpp

item.o: item.cpp item.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o item.o item.cpp

state.o: state.cpp window.h \
		board.h \
		preview.h \
		state.h \
		item.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o state.o state.cpp

moc_window.o: moc_window.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o moc_window.o moc_window.cpp

moc_board.o: moc_board.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o moc_board.o moc_board.cpp

moc_preview.o: moc_preview.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o moc_preview.o moc_preview.cpp

moc_state.o: moc_state.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o moc_state.o moc_state.cpp

####### Install

install:   FORCE

uninstall:   FORCE

FORCE:

